### ISSUE TITLE
Fix "Help improve this page" links

### ISSUE THREAD

**Issue by SteveALee** [w3c/wai-coga-design-guide#8]
Currently the "buttons" link through to the wai-coga-design-guide resource as per all other resources on the WAI site.

As @nitedog pointed out this repo is an internal implementation detail to some extent and the content is managed by the coga TaskForce. 

The "New issue" could go through to the coga repos as long as care is taken with reference to actual content.

But the "fork and Edit on GitHub" is more complex. Ideally it would work on the source content in the coga repo. Perhaps we can code that somehow.

**Comment by SteveALee** [comment]
Meta data has been added to address this but still needs work / deciding. 

``` yaml
github: 
  repository: w3c/wai-coga-design-guide
  path: content-usable/dg/o1p1-clear-purpose.html
feedbackemail: wai@w3.org
```

Fork "button" - `https://github.com/w3c/wai-coga-design-guide/edit/master/content-usable/dg/o1p1-clear-purpose.html`
Issue "button" - `https://github.com/w3c/wai-coga-design-guide/issues/new`

Should be w3c/coga specific. Check with TF

- email - ?
